/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedFamiliasIndexRouteImport } from './routes/_authenticated/familias.index'
import { Route as AuthenticatedFamiliasIdRouteImport } from './routes/_authenticated/familias.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliasIndexRoute =
  AuthenticatedFamiliasIndexRouteImport.update({
    id: '/familias/',
    path: '/familias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliasIdRoute = AuthenticatedFamiliasIdRouteImport.update({
  id: '/familias/$id',
  path: '/familias/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/familia': typeof FamiliaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/familias/': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/familia': typeof FamiliaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/familias': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/familia': typeof FamiliaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/_authenticated/familias/': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/familia'
    | '/admin'
    | '/agenda'
    | '/painel'
    | '/familias/$id'
    | '/familias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/familia'
    | '/admin'
    | '/agenda'
    | '/painel'
    | '/familias/$id'
    | '/familias'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/familia'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/painel'
    | '/_authenticated/familias/$id'
    | '/_authenticated/familias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FamiliaRoute: typeof FamiliaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias/': {
      id: '/_authenticated/familias/'
      path: '/familias'
      fullPath: '/familias/'
      preLoaderRoute: typeof AuthenticatedFamiliasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias/$id': {
      id: '/_authenticated/familias/$id'
      path: '/familias/$id'
      fullPath: '/familias/$id'
      preLoaderRoute: typeof AuthenticatedFamiliasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedFamiliasIdRoute: typeof AuthenticatedFamiliasIdRoute
  AuthenticatedFamiliasIndexRoute: typeof AuthenticatedFamiliasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedFamiliasIdRoute: AuthenticatedFamiliasIdRoute,
  AuthenticatedFamiliasIndexRoute: AuthenticatedFamiliasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FamiliaRoute: FamiliaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
